--- #YAML:1.0
name:         Verilog-Perl
version:      3.468
version_from: Language.pm
abstract:     Verilog language utilities and parsing
license:      perl
installdirs:  site
author:
    - Wilson Snyder <wsnyder@wsnyder.org>
resources:
    homepage: http://www.veripool.org/verilog-perl
    bugtracker: http://www.veripool.org/verilog-perl-bugs
requires:
    Pod::Usage:                    1.34
    Data::Dumper:                  1
    warnings:                      1
build_requires:
    Digest::SHA:                   0
    Test:                          1
    Test::More:                    0
    Time::HiRes:                   1

meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.4.html
    version: 1.4
distribution_type: module
generated_by: hand
